### ISSUE TITLE
More Examples

### ISSUE THREAD

**Issue by cryptodeal** [cryptodeal/zSockets#7]
### What is the problem this feature would solve?

Ideally, `zSockets` should implement all of the examples provided by [uSockets](https://github.com/uNetworking/uSockets/tree/master/examples).

Status (NoSSL):
- [x] Echo Server #6 
- [ ] Hammer Test (WIP) #6
  - execution hangs ~93% complete
  - likely a minor bug in the logic
- [ ] Hammer Test Unix
- [x] HTTP Load Test #8 
- [x] HTTP Server #9 
- [ ] HTTP3 Client
- [ ] HTTP3 Server
- [ ] Peer Verify Test
- [x] TCP Load Test #8 
- [x] TCP Server #10
- [ ] UDP Benchmark

Longer term, the demos should support NoSSL and SSL, but the top priority is to get `zSockets` fully working w/o SSL.

### What is the feature you are proposing to solve the problem?

The addition of these examples will a. make it easier for developers to build with `zSockets` and b. help flush out any bugs that exist in the implementation.

### What alternatives have you considered?

N/A
